# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 18:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
        ('assays', '0030'),
        ('compounds', '0009'),
        ('drugtrials', '0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound')),
                ('concentration_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name=b'Concentration Unit')),
                ('finding_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtrials.FindingResult')),
            ],
        ),
        migrations.RenameField(
            model_name='drugtrial',
            old_name='trial_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='drugtrial',
            name='disease',
            field=models.ManyToManyField(blank=True, to='diseases.Disease'),
        ),
        migrations.AddField(
            model_name='drugtrial',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drugtrial',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugtrial',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound'),
        ),
        migrations.AlterField(
            model_name='drugtrial',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
