# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtrials', '0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findingresult',
            options={'verbose_name': 'Drug Trial Result'},
        ),
        migrations.AddField(
            model_name='findingresult',
            name='notes',
            field=models.CharField(blank=True, default=b'', max_length=2048),
        ),
    ]
