# Generated by Django 2.2.9 on 2020-02-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtrials', '0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('species_name',), 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Species'),
        ),
    ]
