# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 17:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaymethod',
            name='alt_name',
            field=models.CharField(blank=True, default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='assaytarget',
            name='alt_name',
            field=models.CharField(blank=True, default=b'', max_length=1000),
        ),
    ]
