# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 18:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayimage',
            name='assay_plate_id',
            field=models.CharField(default=b'N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='assay_well_id',
            field=models.CharField(default=b'N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='replicate',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
