# Generated by Django 2.1.8 on 2019-04-15 22:35

import assays.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaychipcells',
            name='cell_passage',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Passage#'),
        ),
        migrations.AlterField(
            model_name='assaychipcells',
            name='cellsample_density',
            field=models.FloatField(default=0, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='assaychipcells',
            name='cellsample_density_unit',
            field=models.CharField(choices=[('WE', 'cells / well'), ('CP', 'cells / chip'), ('ML', 'cells / mL'), ('MM', 'cells / mm^2')], default='CP', max_length=8, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='assay_plate_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='assay_well_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='caution_flag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='cross_reference',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='field_id',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='quality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assaychiprawdata',
            name='replicate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='file',
            field=models.FileField(blank=True, help_text='Green = Data from database; Red = Line that will not be read; Gray = Reading with null value ***Uploading overwrites old data***', null=True, upload_to=assays.models.chip_readout_file_location, verbose_name='Data File'),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='notebook',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='readout_start_time',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Readout Start Date'),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='scientist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assaychipreadout',
            name='treatment_time_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Assay Treatment Duration'),
        ),
        migrations.AlterField(
            model_name='assaychipreadoutassay',
            name='assay_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayModel', verbose_name='Assay'),
        ),
        migrations.AlterField(
            model_name='assaychipreadoutassay',
            name='object_type',
            field=models.CharField(blank=True, choices=[('F', 'Field'), ('C', 'Colony'), ('M', 'Media'), ('X', 'Other')], default='F', max_length=6, verbose_name='Object of Interest'),
        ),
        migrations.AlterField(
            model_name='assaychipreadoutassay',
            name='reader_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayReader', verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='assaychipreadoutassay',
            name='readout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayChipReadout', verbose_name='Readout'),
        ),
        migrations.AlterField(
            model_name='assaychipresult',
            name='assay_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayInstance', verbose_name='Assay'),
        ),
        migrations.AlterField(
            model_name='assaychipresult',
            name='result',
            field=models.CharField(choices=[('0', 'Negative'), ('1', 'Positive'), ('x', 'Failed')], default='1', max_length=8, verbose_name='Pos/Neg?'),
        ),
        migrations.AlterField(
            model_name='assaychipresult',
            name='result_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayResultFunction', verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='assaychipresult',
            name='result_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayResultType', verbose_name='Measure'),
        ),
        migrations.AlterField(
            model_name='assaychipresult',
            name='severity',
            field=models.CharField(blank=True, choices=[('-1', 'UNKNOWN'), ('0', 'NEGATIVE'), ('1', '+'), ('2', '+ +'), ('3', '+ + +'), ('4', '+ + + +'), ('5', '+ + + + +')], default='-1', max_length=5, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='assay_chip_id',
            field=models.CharField(max_length=512, verbose_name='Chip ID/ Barcode'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='assay_run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayRun', verbose_name='Study'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='chip_test_type',
            field=models.CharField(choices=[('control', 'Control'), ('compound', 'Compound')], default='control', max_length=8),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='concentration',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Conc.'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.Microdevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='notebook',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='organ_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='Organ Model Name'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='organ_model_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol', verbose_name='Organ Model Protocol'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='scientist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='setup_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='unit',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='conc. Unit'),
        ),
        migrations.AlterField(
            model_name='assaychipsetup',
            name='variance',
            field=models.CharField(blank=True, default='', max_length=3000, verbose_name='Variance from Protocol'),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='chip_readout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayChipReadout', verbose_name='Chip Readout'),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assaychiptestresult',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assaycompoundinstance',
            name='concentration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Concentration Unit'),
        ),
        migrations.AlterField(
            model_name='assaydatafileupload',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaydatafileupload',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaydatafileupload',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaydatapoint',
            name='assay_plate_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaydatapoint',
            name='assay_well_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaydatapoint',
            name='caution_flag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaydatapoint',
            name='cross_reference',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaydatapoint',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaydatapoint',
            name='replicate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaydataupload',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaydataupload',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assaydataupload',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaydataupload',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaydataupload',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assayfailurereason',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assayfailurereason',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayfailurereason',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='assay_plate_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='assay_well_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='field_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assayimage',
            name='replicate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayimagesetting',
            name='color_mapping',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayimagesetting',
            name='label_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assayimagesetting',
            name='label_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='assayimagesetting',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assaylayout',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaylayout',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assaylayout',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaylayout',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaylayout',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='representation',
            field=models.CharField(choices=[('chips', 'Multiple Chips'), ('plate', 'Plate'), ('', '')], max_length=255),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.Microdevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='notebook',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='notebook_page',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='organ_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='organ_model_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol', verbose_name='Model Protocol'),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='scientist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='setup_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='test_type',
            field=models.CharField(choices=[('', '--------'), ('control', 'Control'), ('compound', 'Treated')], max_length=8),
        ),
        migrations.AlterField(
            model_name='assaymatrixitem',
            name='variance_from_organ_model_protocol',
            field=models.CharField(blank=True, default='', max_length=3000, verbose_name='Variance from Protocol'),
        ),
        migrations.AlterField(
            model_name='assaymeasurementtype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaymethod',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assaymethod',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaymethod',
            name='protocol_file',
            field=models.FileField(blank=True, null=True, upload_to='assays'),
        ),
        migrations.AlterField(
            model_name='assaymodel',
            name='assay_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assaymodel',
            name='assay_protocol_file',
            field=models.FileField(blank=True, null=True, upload_to='assays', verbose_name='Protocol File'),
        ),
        migrations.AlterField(
            model_name='assaymodel',
            name='assay_short_name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='assaymodel',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaymodel',
            name='test_type',
            field=models.CharField(choices=[('TOX', 'Toxicity'), ('DM', 'Disease'), ('EFF', 'Efficacy'), ('CC', 'Cell Characterization')], max_length=13, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='assaymodel',
            name='version_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='assaymodeltype',
            name='assay_type_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assaymodeltype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayplatecells',
            name='cell_passage',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Passage#'),
        ),
        migrations.AlterField(
            model_name='assayplatecells',
            name='cellsample_density',
            field=models.FloatField(default=0, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='assayplatecells',
            name='cellsample_density_unit',
            field=models.CharField(choices=[('WE', 'cells/well'), ('ML', 'cells/mL'), ('MM', 'cells/mm^2')], default='WE', max_length=8, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assays.models.plate_readout_file_location, verbose_name='Data File'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='notebook',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='readout_start_time',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Readout Date'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='scientist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assayplatereadout',
            name='treatment_time_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Treatment Duration'),
        ),
        migrations.AlterField(
            model_name='assayplatereadoutassay',
            name='assay_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayModel', verbose_name='Assay'),
        ),
        migrations.AlterField(
            model_name='assayplatereadoutassay',
            name='reader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayReader', verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='assayplatereadoutassay',
            name='readout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReadout', verbose_name='Readout'),
        ),
        migrations.AlterField(
            model_name='assayplateresult',
            name='assay_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReadoutAssay', verbose_name='Assay'),
        ),
        migrations.AlterField(
            model_name='assayplateresult',
            name='result',
            field=models.CharField(choices=[('0', 'Negative'), ('1', 'Positive'), ('x', 'Failed')], default='1', max_length=8, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='assayplateresult',
            name='result_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayResultFunction', verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='assayplateresult',
            name='result_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayResultType', verbose_name='Measure'),
        ),
        migrations.AlterField(
            model_name='assayplateresult',
            name='severity',
            field=models.CharField(blank=True, choices=[('-1', 'UNKNOWN'), ('0', 'NEGATIVE'), ('1', '+'), ('2', '+ +'), ('3', '+ + +'), ('4', '+ + + +'), ('5', '+ + + + +')], default='-1', max_length=5, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='assay_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayLayout', verbose_name='Assay Layout'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='assay_plate_id',
            field=models.CharField(max_length=512, verbose_name='Plate ID/ Barcode'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='assay_run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayRun', verbose_name='Study'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='notebook',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='scientist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assayplatesetup',
            name='setup_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='readout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReadout', verbose_name='Plate ID/ Barcode'),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assayplatetestresult',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assayqualityindicator',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayreader',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayreadout',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayreadout',
            name='quality',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='assayresultfunction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='assayresultfunction',
            name='function_results',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assayresultfunction',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayresulttype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='assayresulttype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='access_groups',
            field=models.ManyToManyField(blank=True, help_text='Level 2 Access Groups Assignation', related_name='access_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='assay_run_id',
            field=models.TextField(help_text="Standard format 'CenterID-YYYY-MM-DD-Name-###'", unique=True, verbose_name='Study ID'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='bulk_file',
            field=models.FileField(blank=True, null=True, upload_to=assays.models.bulk_readout_file_location, verbose_name='Data File'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group (Level 0)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studies'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='name',
            field=models.TextField(default='Study-01', help_text='Name-###', verbose_name='Study Name'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='protocol',
            field=models.FileField(blank=True, help_text='Protocol File for Study', null=True, upload_to='study_protocol', verbose_name='Protocol File'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to selected group. Unchecked sends to Level 3'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='signed_off_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='start_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='assayrun',
            name='use_in_calculations',
            field=models.BooleanField(default=False, help_text='Set this to True if this data should be included in Compound Reports and other data aggregations.'),
        ),
        migrations.AlterField(
            model_name='assayrunstakeholder',
            name='signed_off_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaysamplelocation',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaysetting',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaysetupcell',
            name='density',
            field=models.FloatField(default=0, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='assaysetupcell',
            name='passage',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Passage#'),
        ),
        migrations.AlterField(
            model_name='assaysetupcompound',
            name='concentration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Concentration Unit'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='bulk_file',
            field=models.FileField(blank=True, null=True, upload_to=assays.models.upload_file_location, verbose_name='Data File'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='description',
            field=models.CharField(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='group',
            field=models.ForeignKey(help_text='Select the Data Group. The study will be bound to this group', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Data Group'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studies'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Study Name'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='protocol',
            field=models.FileField(blank=True, help_text='Protocol File for Study', null=True, upload_to='study_protocol', verbose_name='Protocol File'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='repro_nums',
            field=models.CharField(blank=True, default='', help_text='Excellent|Acceptable|Poor', max_length=40),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Check box to restrict to the Access Groups selected below. Access is granted to access group(s) after Data Group admin and all designated Stakeholder Group admin(s) sign off on the study'),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='signed_off_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='start_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='assaystudyconfiguration',
            name='hardware_description',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='assaystudyconfiguration',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaystudyconfiguration',
            name='media_composition',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='assaystudymodel',
            name='integration_mode',
            field=models.CharField(choices=[('0', 'Functional'), ('1', 'Physical')], default='1', max_length=13),
        ),
        migrations.AlterField(
            model_name='assaystudymodel',
            name='output',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assaystudystakeholder',
            name='signed_off_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assaystudysupportingdata',
            name='description',
            field=models.CharField(help_text='Describes the contents of the supporting data file', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assaystudysupportingdata',
            name='supporting_data',
            field=models.FileField(help_text='Supporting Data for Study', upload_to=assays.models.study_supporting_data_location),
        ),
        migrations.AlterField(
            model_name='assaysupplier',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaytarget',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assaytarget',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaywelltype',
            name='background_color',
            field=models.CharField(help_text='Provide color code or name. You can pick one from: http://www.w3schools.com/html/html_colornames.asp', max_length=20),
        ),
        migrations.AlterField(
            model_name='assaywelltype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assaywelltype',
            name='well_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='physicalunits',
            name='availability',
            field=models.CharField(blank=True, default='', help_text='Type a series of strings for indicating where this unit should be listed:\ntest = test results\nreadouts = readouts\ncells = cell samples', max_length=255),
        ),
        migrations.AlterField(
            model_name='physicalunits',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='physicalunits',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='studysupportingdata',
            name='description',
            field=models.CharField(help_text='Describes the contents of the supporting data file', max_length=1000),
        ),
        migrations.AlterField(
            model_name='studysupportingdata',
            name='supporting_data',
            field=models.FileField(help_text='Supporting Data for Study', upload_to=assays.models.study_supporting_data_location),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
    ]
