# Generated by Django 2.1.8 on 2019-05-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('assays', '0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaystudy',
            name='collaborator_groups',
            field=models.ManyToManyField(blank=True, related_name='study_collaborator_groups', to='auth.Group'),
        ),
    ]
