# Generated by Django 2.1.11 on 2019-09-09 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microdevices', '0017'),
        ('assays', '0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)')),
                ('flagged', models.BooleanField(default=False, help_text='Check box to flag for review')),
                ('reason_for_flag', models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assaycategory_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assaycategory_modified_by', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assaycategory_signed_off_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assay Category',
                'verbose_name_plural': 'Assay Categories',
            },
        ),
        migrations.AddField(
            model_name='assaystudy',
            name='organ_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel'),
        ),
        migrations.AddField(
            model_name='assaystudy',
            name='organ_model_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol'),
        ),
        migrations.AddField(
            model_name='assaytarget',
            name='methods',
            field=models.ManyToManyField(to='assays.AssayMethod'),
        ),
        migrations.AlterField(
            model_name='assaysetupcell',
            name='biosensor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Biosensor'),
        ),
        migrations.AddField(
            model_name='assaycategory',
            name='targets',
            field=models.ManyToManyField(to='assays.AssayTarget'),
        ),
    ]
