# Generated by Django 2.1.9 on 2019-10-14 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayPlateReaderMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)')),
                ('flagged', models.BooleanField(default=False, help_text='Check box to flag for review')),
                ('reason_for_flag', models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('device', models.CharField(blank=True, choices=[(24, '24 Well Plate'), (96, '96 Well Plate'), (384, '384 Well Plate')], default=24, max_length=20, verbose_name='Plate Size')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_modified_by', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_signed_off_by', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name_plural': 'Assay Plate Reader Map',
            },
        ),
        migrations.CreateModel(
            name='AssayPlateReaderMapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)')),
                ('flagged', models.BooleanField(default=False, help_text='Check box to flag for review')),
                ('reason_for_flag', models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300)),
                ('name', models.CharField(blank=True, default='none', max_length=100)),
                ('row_index', models.IntegerField(blank=True, default=1)),
                ('column_index', models.IntegerField(blank=True, default=1)),
                ('sample_replicate', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('well_use', models.CharField(blank=True, choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use')),
                ('time_unit', models.CharField(blank=True, choices=[('day', 'day'), ('hour', 'hour'), ('minute', 'minute')], default='day', max_length=8, verbose_name='Unit')),
                ('time', models.FloatField(blank=True, default=0)),
                ('assayvalue', models.FloatField(blank=True, null=True)),
                ('assayplatereadermap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMap')),
                ('assayvalue_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Reporting Unit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermapitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('matrix_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayMatrixItem')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermapitem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('sample_location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermapitem_signed_off_by', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Map Item',
            },
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapitem',
            unique_together={('assayplatereadermap', 'row_index', 'column_index')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermap',
            unique_together={('study', 'name')},
        ),
    ]
