# Generated by Django 2.1.9 on 2019-10-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayPlateReaderMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)')),
                ('flagged', models.BooleanField(default=False, help_text='Check box to flag for review')),
                ('reason_for_flag', models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('device', models.IntegerField(blank=True, choices=[(24, '24 Well Plate'), (96, '96 Well Plate'), (384, '384 Well Plate')], default=24, verbose_name='Device Size')),
                ('time_unit', models.CharField(blank=True, choices=[('day', 'Day'), ('hour', 'Hour'), ('minute', 'Minute')], default='day', max_length=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_modified_by', to=settings.AUTH_USER_MODEL)),
                ('plate_reader_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_signed_off_by', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name_plural': 'Assay Plate Reader Map',
            },
        ),
        migrations.CreateModel(
            name='AssayPlateReaderMapDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('plate_reader_file_location', models.URLField(blank=True, null=True)),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Imported Files',
            },
        ),
        migrations.CreateModel(
            name='AssayPlateReaderMapDataFileBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Block Name')),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('data_block', models.IntegerField(default=1, null=True)),
                ('processing_set', models.IntegerField(null=True)),
                ('assayplatereadermap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMap')),
                ('assayplatereadermapdatafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapDataFile')),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Data Blocks',
            },
        ),
        migrations.CreateModel(
            name='AssayPlateReaderMapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='none', max_length=100)),
                ('row_index', models.IntegerField(blank=True, default=999)),
                ('column_index', models.IntegerField(blank=True, default=999)),
                ('plate_index', models.IntegerField(blank=True, default=999)),
                ('well_use', models.CharField(blank=True, choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use')),
                ('standard_value', models.FloatField(blank=True, null=True)),
                ('assayplatereadermap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMap')),
                ('location', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation')),
                ('matrix_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayMatrixItem')),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Map Item',
            },
        ),
        migrations.CreateModel(
            name='AssayPlateReaderMapItemValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(blank=True, default=999)),
                ('column_index', models.IntegerField(blank=True, default=999)),
                ('plate_index', models.IntegerField(blank=True, default=999)),
                ('well_use', models.CharField(blank=True, choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use')),
                ('value', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, default=0)),
                ('caution_flag', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('excluded', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('replicate', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('assayplatereadermap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMap')),
                ('assayplatereadermapdatafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapDataFile')),
                ('assayplatereadermapdatafileblock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapDataFileBlock')),
                ('matrix_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayMatrixItem')),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Map Instance (one set for each data block)',
            },
        ),
        migrations.CreateModel(
            name='AbstractClassAssayStudyAssay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('assays.assaystudyassay',),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='study_assay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudyAssay'),
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapitemvalue',
            unique_together={('study', 'assayplatereadermap', 'assayplatereadermapdatafile', 'assayplatereadermapdatafileblock', 'plate_index', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapitem',
            unique_together={('study', 'assayplatereadermap', 'plate_index')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapdatafileblock',
            unique_together={('study', 'data_block', 'assayplatereadermapdatafile')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapdatafile',
            unique_together={('study', 'plate_reader_file_location')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermap',
            unique_together={('study', 'name')},
        ),
    ]
