# Generated by Django 2.1.9 on 2019-10-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0038_auto_20190926_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayplatemapitem',
            old_name='study',
            new_name='study_id',
        ),
    ]
