# Generated by Django 2.1.9 on 2019-10-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0038_auto_20191028_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayPlateReaderMapOtherItemValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_use', models.CharField(blank=True, choices=[('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use')),
                ('plate_index', models.IntegerField(blank=True, default=999)),
                ('value', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Map Non-Sample Item Values',
            },
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapblankitemvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapblankitemvalue',
            name='assayplatereadermap',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapblankitemvalue',
            name='assayplatereadermapdatafile',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapblankitemvalue',
            name='assayplatereadermapdatafileblock',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapblankitemvalue',
            name='assayplatereadermapitem',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapblankitemvalue',
            name='study',
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapstandarditemvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapstandarditemvalue',
            name='assayplatereadermap',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapstandarditemvalue',
            name='assayplatereadermapdatafile',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapstandarditemvalue',
            name='assayplatereadermapdatafileblock',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapstandarditemvalue',
            name='assayplatereadermapitem',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapstandarditemvalue',
            name='study',
        ),
        migrations.AlterModelOptions(
            name='assayplatereadermapdatafileblock',
            options={'verbose_name': 'Assay Plate Reader Data Blocks'},
        ),
        migrations.AlterModelOptions(
            name='assayplatereadermapsampleitemvalue',
            options={'verbose_name': 'Assay Plate Reader Map Sample Item Values'},
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='device',
            field=models.IntegerField(blank=True, choices=[(24, '24 Well Plate'), (96, '96 Well Plate'), (384, '384 Well Plate')], default=24, verbose_name='Device Size'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='plate_reader_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('hour', 'Hour'), ('minute', 'Minute')], default='day', max_length=8),
        ),
        migrations.DeleteModel(
            name='AssayPlateReaderMapBlankItemValue',
        ),
        migrations.DeleteModel(
            name='AssayPlateReaderMapStandardItemValue',
        ),
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMap'),
        ),
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermapdatafile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapDataFile'),
        ),
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermapdatafileblock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapDataFileBlock'),
        ),
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermapitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapItem'),
        ),
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy'),
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapotheritemvalue',
            unique_together={('study', 'assayplatereadermap', 'assayplatereadermapdatafile', 'assayplatereadermapdatafileblock', 'plate_index', 'time')},
        ),
    ]
