# Generated by Django 2.2.10 on 2020-05-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellsamples', '0010'),
        ('drugtrials', '0011'),
        ('assays', '0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_mass', models.FloatField(blank=True, help_text='Body Mass', null=True, verbose_name='Body Mass (kg)')),
                ('total_organ_weight', models.FloatField(blank=True, help_text='Total Organ Weight', null=True, verbose_name='Total Organ Weight (g)')),
                ('organ_tissue', models.FloatField(blank=True, help_text='Organ Tissue', null=True, verbose_name='Organ Tissue (cells/g)')),
                ('plasma_volume', models.FloatField(blank=True, help_text='Plasma Volume', null=True, verbose_name='VP (L)')),
                ('vp', models.FloatField(blank=True, help_text='Plasma Volume', null=True, verbose_name='VP (L/kg)')),
                ('ve', models.FloatField(blank=True, help_text='Extracellular Volume', null=True, verbose_name='VE (L/kg)')),
                ('rei', models.FloatField(blank=True, help_text='Extravascular/Intravascular Ratio', null=True, verbose_name='RE/I')),
                ('vr', models.FloatField(blank=True, help_text='Volume of Drug Distribution Minus Extracellular Space', null=True, verbose_name='VR')),
                ('absorptive_surface_area', models.FloatField(blank=True, help_text='Absorptive Surface Area (m^2)', null=True, verbose_name='Absorptive Surface Area')),
                ('ki', models.FloatField(blank=True, help_text='Inverse of Small Intestine Transit Time', null=True, verbose_name='Ki (1/min)')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Organ', verbose_name='Organ')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayReference', verbose_name='Reference')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtrials.Species', verbose_name='Species')),
            ],
        ),
    ]
