# Generated by Django 2.1.9 on 2019-10-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0038_auto_20191005_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='sample_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='time_unit',
            field=models.CharField(choices=[('day', 'day'), ('hour', 'hour'), ('minute', 'minute')], default='dy', max_length=8, verbose_name='Unit'),
        ),
    ]
