# Generated by Django 2.1.9 on 2019-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0039_auto_20191029_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='column_index',
            field=models.IntegerField(blank=True, default=999),
        ),
        migrations.AddField(
            model_name='assayplatereadermapotheritemvalue',
            name='row_index',
            field=models.IntegerField(blank=True, default=999),
        ),
        migrations.AddField(
            model_name='assayplatereadermapsampleitemvalue',
            name='column_index',
            field=models.IntegerField(blank=True, default=999),
        ),
        migrations.AddField(
            model_name='assayplatereadermapsampleitemvalue',
            name='row_index',
            field=models.IntegerField(blank=True, default=999),
        ),
    ]
