# Generated by Django 2.1.9 on 2019-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0039_assayplatereadermapitemvalue_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assayplatereadermapdatafileblock',
            options={'verbose_name': 'Assay Plate Reader Data Block'},
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafileblock',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='File and Block Name'),
        ),
    ]
