# Generated by Django 2.1.9 on 2019-10-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0039_auto_20191007_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='column_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='row_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='time_unit',
            field=models.CharField(choices=[('day', 'day'), ('hour', 'hour'), ('minute', 'minute')], default='day', max_length=8, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='well_use',
            field=models.CharField(choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use'),
        ),
    ]
