# Generated by Django 2.1.9 on 2019-10-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0039_assayplatereadermap_study_assay'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayPlateReaderMapItemDataFileBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_block', models.IntegerField(default=1, null=True)),
                ('process_group', models.IntegerField(null=True)),
                ('data_file_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayDataFileUpload')),
                ('study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy')),
            ],
            options={
                'verbose_name': 'Assay Plate Reader Imported Files',
            },
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='reason_for_flag',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='signed_off_by',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermap',
            name='signed_off_date',
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='base_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Base Plate Map Name'),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='plate_use',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('mix', 'Mix')], default='one', max_length=10, verbose_name='Sample Times'),
        ),
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='caution_flag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='replicate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Specific Plate Map Name'),
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='reason_for_flag',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='signed_off_by',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='signed_off_date',
        ),
        migrations.AddField(
            model_name='assayplatereadermapitem',
            name='assayplatereadermapitemdatafileblock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMapItemDataFileBlock'),
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapitem',
            unique_together={('study', 'assayplatereadermap', 'plate_index')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatereadermapitemdatafileblock',
            unique_together={('study', 'data_file_block', 'data_file_upload')},
        ),
    ]
