# Generated by Django 2.1.9 on 2019-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0039_auto_20191001_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatemapitem',
            name='sample_replicate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
    ]
