# Generated by Django 2.1.9 on 2019-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0039_auto_20191014_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayplatereadermapitem',
            old_name='assayvalue',
            new_name='standard_value',
        ),
        migrations.RenameField(
            model_name='assayplatereadermapitem',
            old_name='assayvalue_unit',
            new_name='standard_value_unit',
        ),
    ]
