# Generated by Django 2.1.9 on 2019-10-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0040_auto_20191009_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='sample_location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation'),
        ),
    ]
