# Generated by Django 2.1.9 on 2019-10-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0040_auto_20191023_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='caution_flag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='excluded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='replicate',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
