# Generated by Django 2.1.9 on 2019-10-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0040_auto_20191001_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayplatemap',
            old_name='study',
            new_name='study_id',
        ),
        migrations.RenameField(
            model_name='assayplatemapitem',
            old_name='plate_map',
            new_name='aplatemap_id',
        ),
        migrations.AlterUniqueTogether(
            name='assayplatemap',
            unique_together={('study_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='assayplatemapitem',
            unique_together={('aplatemap_id', 'name')},
        ),
    ]
