# Generated by Django 2.2.15 on 2020-09-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microdevices', '0020'),
        ('compounds', '0012'),
        ('cellsamples', '0011'),
        ('assays', '0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaymatrix',
            name='organ_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='MPS Model'),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.Microdevice', verbose_name='Plate Type'),
        ),
        migrations.AlterField(
            model_name='assaymatrix',
            name='representation',
            field=models.CharField(choices=[('chips', 'Multiple Chips'), ('plate', 'Plate')], max_length=255, verbose_name='Representation'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200917-22:46:23', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='assaystudy',
            name='use_in_calculations',
            field=models.BooleanField(default=False, help_text='Check this if this data should be included in Compound Reports and other data aggregations.', verbose_name='Use Data in Compound Report'),
        ),
        migrations.CreateModel(
            name='AssayGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('test_type', models.CharField(choices=[('', '--------'), ('control', 'Control'), ('compound', 'Treated')], max_length=8, verbose_name='Test Type')),
                ('organ_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='MPS Model')),
                ('organ_model_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol', verbose_name='MPS Model Version')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy', verbose_name='Study')),
            ],
            options={
                'unique_together': {('name', 'study')},
            },
        ),
        migrations.AddField(
            model_name='assaymatrixitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayGroup', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='AssayGroupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('addition_time', models.FloatField(blank=True, verbose_name='Addition Time')),
                ('duration', models.FloatField(blank=True, verbose_name='Duration')),
                ('addition_location', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Addition Location')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayGroup', verbose_name='Group')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySetting', verbose_name='Setting')),
                ('unit', models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Unit')),
            ],
            options={
                'unique_together': {('group', 'setting', 'addition_location', 'unit', 'addition_time', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='AssayGroupCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(verbose_name='Concentration')),
                ('addition_time', models.FloatField(blank=True, verbose_name='Addition Time')),
                ('duration', models.FloatField(blank=True, verbose_name='Duration')),
                ('addition_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Addition Location')),
                ('compound_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CompoundInstance', verbose_name='Compound Instance')),
                ('concentration_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Concentration Unit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayGroup', verbose_name='Group')),
            ],
            options={
                'unique_together': {('group', 'compound_instance', 'concentration', 'concentration_unit', 'addition_time', 'duration', 'addition_location')},
            },
        ),
        migrations.CreateModel(
            name='AssayGroupCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField(default=0, verbose_name='density')),
                ('passage', models.CharField(blank=True, default='', max_length=16, verbose_name='Passage#')),
                ('addition_time', models.FloatField(blank=True, null=True, verbose_name='Addition Time')),
                ('addition_location', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Addition Location')),
                ('biosensor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Biosensor', verbose_name='Biosensor')),
                ('cell_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellSample', verbose_name='Cell Sample')),
                ('density_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Density Unit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayGroup', verbose_name='Group')),
            ],
            options={
                'unique_together': {('group', 'cell_sample', 'biosensor', 'density', 'density_unit', 'passage', 'addition_time', 'addition_location')},
            },
        ),
    ]
