# Generated by Django 2.1.9 on 2019-10-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0040_auto_20191031_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assayplatereadermapdatafile',
            options={'verbose_name': 'Assay Plate Reader Imported File'},
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafileblock',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Block Name'),
        ),
    ]
