# Generated by Django 2.1.9 on 2019-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0040_auto_20191029_1401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assayplatereadermapotheritemvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermap',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermapdatafile',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermapdatafileblock',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapotheritemvalue',
            name='assayplatereadermapitem',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapotheritemvalue',
            name='study',
        ),
        migrations.AlterModelOptions(
            name='assayplatereadermapitemvalue',
            options={'verbose_name': 'Assay Plate Reader Map Instance (one for each data block)'},
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='assayplatereadermapitem',
        ),
        migrations.AddField(
            model_name='assayplatereadermapitemvalue',
            name='well_use',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use'),
        ),
        migrations.DeleteModel(
            name='AssayPlateReaderMapOtherItemValue',
        ),
    ]
