# Generated by Django 2.1.9 on 2019-10-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0041_auto_20191024_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatereadermap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermap_signed_off_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='signed_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
