# Generated by Django 2.1.9 on 2019-10-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0041_auto_20191001_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayplatemapitem',
            old_name='matrix_item',
            new_name='matrix_item_id',
        ),
    ]
