# Generated by Django 2.1.9 on 2019-10-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0041_auto_20191009_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
