# Generated by Django 2.1.9 on 2019-10-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0042_auto_20191009_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='assayplatereadermap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayPlateReaderMap'),
            preserve_default=False,
        ),
    ]
