# Generated by Django 2.2.15 on 2020-11-06 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermapdatafile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermapdatafile_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayplatereadermapdatafile_signed_off_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafile',
            name='signed_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assayomicdatafileupload',
            name='description',
            field=models.CharField(default='file added - 20201106-18:11:23', help_text='Description of the data being uploaded in this file (e.g., "Treated vrs Control" or "Treated with 1uM Calcifidiol".', max_length=2000, verbose_name='Data Description'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20201106-18:11:23', max_length=2000, null=True),
        ),
    ]
