# Generated by Django 2.1.9 on 2019-10-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0042_assayplatereadermapitem_plate_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('hour', 'Hour'), ('minute', 'Minute')], default='day', max_length=8, verbose_name='Unit'),
        ),
    ]
