# Generated by Django 2.1.9 on 2019-10-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0042_auto_20191001_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatemapitem',
            name='rawvalue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assayplatemapitem',
            name='rawvalue_unit_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Concentration Unit'),
            preserve_default=False,
        ),
    ]
