# Generated by Django 2.1.9 on 2019-10-10 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0043_auto_20191009_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='device',
            field=models.CharField(blank=True, choices=[('24', '24 Well Plate'), ('96', '96 Well Plate'), ('384', '384 Well Plate')], default='96', max_length=20, verbose_name='Plate Size'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy'),
        ),
    ]
