# Generated by Django 2.2.15 on 2020-11-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaystudy',
            name='release_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='assayomicdatafileupload',
            name='description',
            field=models.CharField(default='file added - 20201123-16:29:16', help_text='Description of the data being uploaded in this file (e.g., "Treated vrs Control" or "Treated with 1uM Calcifidiol".', max_length=2000, verbose_name='Data Description'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20201123-16:29:16', max_length=2000, null=True),
        ),
    ]
