# Generated by Django 2.1.9 on 2019-10-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0044_auto_20191017_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='location',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation'),
        ),
    ]
