# Generated by Django 2.1.9 on 2019-10-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0044_auto_20191009_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='assayvalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='assayvalue_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Reporting Unit'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='column_index',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='row_index',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='sample_replicate',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('hour', 'hour'), ('minute', 'minute')], default='day', max_length=8, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='well_use',
            field=models.CharField(blank=True, choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use'),
        ),
    ]
