# Generated by Django 2.1.9 on 2019-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0045_auto_20191018_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='plate_index',
            field=models.IntegerField(blank=True, default=999),
        ),
    ]
