# Generated by Django 2.1.9 on 2019-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0045_auto_20191010_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='device',
            field=models.CharField(blank=True, choices=[(24, '24 Well Plate'), (96, '96 Well Plate'), (384, '384 Well Plate')], default=24, max_length=20, verbose_name='Plate Size'),
        ),
    ]
