# Generated by Django 2.1.9 on 2019-10-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0045_auto_20191001_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatemapitem',
            name='rawvalue_unit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Reporting Unit'),
        ),
    ]
