# Generated by Django 2.1.9 on 2019-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0046_auto_20191019_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='column_index',
            field=models.IntegerField(blank=True, default=999),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='row_index',
            field=models.IntegerField(blank=True, default=999),
        ),
    ]
