# Generated by Django 2.1.9 on 2019-10-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0046_auto_20191001_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assayplatemapitem',
            unique_together={('aplatemap_id', 'row_index', 'column_index')},
        ),
    ]
