# Generated by Django 2.1.9 on 2019-10-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0047_auto_20191001_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayplatemapitem',
            old_name='aplatemap_id',
            new_name='assayplatemap_id',
        ),
        migrations.AlterUniqueTogether(
            name='assayplatemapitem',
            unique_together={('assayplatemap_id', 'row_index', 'column_index')},
        ),
    ]
