# Generated by Django 2.1.9 on 2019-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0047_auto_20191019_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='device',
            field=models.IntegerField(blank=True, choices=[(24, '24 Well Plate'), (96, '96 Well Plate'), (384, '384 Well Plate')], default=384, verbose_name='Plate Size'),
        ),
    ]
