# Generated by Django 2.2.13 on 2021-01-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0048_auto_20210113_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayomicdatafileupload',
            name='description',
            field=models.CharField(default='file added - 20210122-11:17:19', help_text='A description of the data being uploaded in this file (e.g., "Treated vrs Control" or "Treated with 1uM Calcifidiol".', max_length=2000, verbose_name='Data Description'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20210122-11:17:19', max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='AssayOmicSampleMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(default='', help_text='The sample name - must match EXACTLY the headers found in the omic counts data files', max_length=255, verbose_name='Cross Reference')),
                ('sample_time', models.FloatField(default=0, verbose_name='Time')),
                ('matrix_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayMatrixItem', verbose_name='Matrix Item')),
                ('sample_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Sample Location')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudy', verbose_name='Study')),
            ],
            options={
                'verbose_name': 'Omic Sample Name and Metadata',
                'unique_together': {('study', 'sample_name')},
            },
        ),
    ]
