# Generated by Django 2.1.9 on 2019-10-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0048_auto_20191002_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assayplatemapitem',
            name='rawvalue',
        ),
        migrations.RemoveField(
            model_name='assayplatemapitem',
            name='rawvalue_unit_id',
        ),
    ]
