# Generated by Django 2.1.9 on 2019-10-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0049_auto_20191020_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractClassAssayStudyAssay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('assays.assaystudyassay',),
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitem',
            name='replicate',
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='study_assay',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudyAssay'),
            preserve_default=False,
        ),
    ]
