# Generated by Django 2.1.9 on 2019-10-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0049_auto_20191002_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatemapitem',
            name='assayvalue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assayplatemapitem',
            name='assayvalue_unit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Reporting Unit'),
            preserve_default=False,
        ),
    ]
