# Generated by Django 2.1.9 on 2019-10-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0050_auto_20191022_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='study_assay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assays.AssayStudyAssay'),
        ),
    ]
