# Generated by Django 2.1.9 on 2020-01-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0060_auto_20200110_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatereadermap',
            name='standard_unit',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200115-17:40:34', max_length=2000, null=True),
        ),
    ]
