# Generated by Django 2.1.9 on 2020-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0062_auto_20200115_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assayplatereadermapdatafileblock',
            name='assayplatereadermapdataprocessing',
        ),
        migrations.AddField(
            model_name='assayplatereadermapdatafileblock',
            name='data_processing_parsable',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200220-08:00:44', max_length=2000, null=True),
        ),
    ]
