# Generated by Django 2.1.9 on 2020-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0063_auto_20200220_0800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assayplatereadermapdataprocessing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapdataprocessing',
            name='study',
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200221-08:05:40', max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='AssayPlateReaderMapDataProcessing',
        ),
    ]
