# Generated by Django 2.1.9 on 2020-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0065_auto_20200221_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200221-08:40:15', max_length=2000, null=True),
        ),
    ]
