# Generated by Django 2.1.9 on 2020-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0066_auto_20200221_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayplatereadermap',
            name='standard_molecular_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assayplatereadermap',
            name='well_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200301-06:49:12', max_length=2000, null=True),
        ),
    ]
