# Generated by Django 2.1.9 on 2020-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0067_auto_20200301_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='adjusted_value',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='caution_flag',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='excluded',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='fitted_value',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assayplatereadermapitemvalue',
            name='replicate',
        ),
        migrations.AlterField(
            model_name='assayplatereadermap',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('minute', 'Minute'), ('hour', 'Hour')], default='day', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200310-15:58:17', max_length=2000, null=True),
        ),
    ]
