# Generated by Django 2.1.9 on 2020-04-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0069_auto_20200427_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayplatereadermapdatafile',
            name='description',
            field=models.CharField(blank=True, default='file added - 20200429-10:30:36', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='collection_time',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='collection_volume',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitem',
            name='well_use',
            field=models.CharField(blank=True, choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use'),
        ),
        migrations.AlterField(
            model_name='assayplatereadermapitemvalue',
            name='well_use',
            field=models.CharField(blank=True, choices=[('sample', 'Sample'), ('standard', 'Standard'), ('blank', 'Blank'), ('empty', 'Empty/Unused')], default='empty', max_length=8, verbose_name='Well Use'),
        ),
    ]
