# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='absorption',
            field=models.CharField(blank=True, default='', help_text='Absorption Description from DrugBank', max_length=1000, verbose_name='Absorption'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='acidic_pka',
            field=models.FloatField(blank=True, help_text='The most acidic pKa calculated using ACDlabs.', null=True, verbose_name='Acidic pKa (ACD)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='alogp',
            field=models.FloatField(blank=True, help_text='Calculated ALogP.', null=True, verbose_name='ALogP'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='basic_pka',
            field=models.FloatField(blank=True, help_text='The most basic pKa calculated using ACDlabs.', null=True, verbose_name='Basic pKa (ACD)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='bioavailability',
            field=models.CharField(blank=True, default='', help_text='Bioavailability from DrugBank', max_length=20, verbose_name='Bioavailability'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='chemblid',
            field=models.CharField(blank=True, default='', help_text='Enter a ChEMBL id, e.g. CHEMBL25, and click Retrieve to get compound information automatically.', max_length=20, verbose_name='ChEMBL ID'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='clearance',
            field=models.CharField(blank=True, default='', help_text='Clearance from DrugBank', max_length=500, verbose_name='Clearance'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='clinical',
            field=models.CharField(blank=True, default='', help_text='Summary of clinical findings', max_length=1000, verbose_name='Clinical Findings'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='drug_class',
            field=models.CharField(blank=True, default='', help_text='Drug Class from DrugBank', max_length=150, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='drugbank_id',
            field=models.CharField(blank=True, default='', help_text='DrugBank ID', max_length=20, verbose_name='DrugBank ID'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='epa',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the EPA project'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='half_life',
            field=models.CharField(blank=True, default='', help_text='Half Life from DrugBank', max_length=100, verbose_name='Half Life'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchikey',
            field=models.CharField(blank=True, default='', help_text='IUPAC standard InChI key for the compound', max_length=27, verbose_name='InChI key'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='known_drug',
            field=models.BooleanField(default=False, verbose_name='Known drug?'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='last_update',
            field=models.DateField(blank=True, help_text='Last time when activities associated with the compound were updated.', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='logd',
            field=models.FloatField(blank=True, help_text='The calculated octanol/water distribution coefficient at pH7.4 using ACDlabs.', null=True, verbose_name='LogD (ACD)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='logp',
            field=models.FloatField(blank=True, help_text='The calculated octanol/water partition coefficient using ACDlabs', null=True, verbose_name='LogP (ACD)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='medchem_alerts',
            field=models.BooleanField(default=False, verbose_name='Inicates whether structural alerts are listed for this compound'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_formula',
            field=models.CharField(blank=True, default='', help_text='Molecular formula of compound.', max_length=40),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.FloatField(blank=True, help_text='Molecular weight of the compound', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='mps',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the MPS project'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(help_text='Preferred compound name.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='pk_metabolism',
            field=models.CharField(blank=True, default='', help_text='Summary of pharmacokinetics and metabolism', max_length=1000, verbose_name='PK/Metabolism'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='post_marketing',
            field=models.CharField(blank=True, default='', help_text='Summary of post-marketing findings', max_length=1000, verbose_name='Post-marketing'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='preclinical',
            field=models.CharField(blank=True, default='', help_text='Summary of pre-clinical findings', max_length=1000, verbose_name='Pre-clinical Findings'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='protein_binding',
            field=models.CharField(blank=True, default='', help_text='Protein Binding from DrugBank', max_length=20, verbose_name='Protein Binding'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='pubchemid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='PubChem ID'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='ro3_passes',
            field=models.BooleanField(default=False, help_text='Rule of 3 passes.  It is suggested that compounds that pass all these criteria aremore likely to be hits in fragment screening.', verbose_name='Passes rule of 3?'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='ro5_violations',
            field=models.IntegerField(blank=True, help_text="Number of properties defined in Lipinski's Rule of 5 (RO5) that the compound fails.", null=True, verbose_name='Rule of 5 violations'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='rotatable_bonds',
            field=models.IntegerField(blank=True, help_text='Number of rotatable bonds.', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, default='', help_text='Canonical smiles, generated using pipeline pilot.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='compound',
            name='species',
            field=models.CharField(blank=True, default='', help_text='A description of the predominant species occurring at pH 7.4 and can be acid, base, neutral or zwitterion.', max_length=10, verbose_name='Molecular species'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='synonyms',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='compound',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Tags for the compound (EPA, NCATS, etc.)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='tctc',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the TCTC project'),
        ),
        migrations.AlterField(
            model_name='compoundinstance',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='compoundsupplier',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='action',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='uniprot_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='summarytype',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='summarytype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
    ]
