# Generated by Django 2.2.9 on 2020-02-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compound',
            options={'ordering': ('name',), 'verbose_name': 'Compound'},
        ),
        migrations.AlterField(
            model_name='compound',
            name='bioavailability',
            field=models.CharField(blank=True, default='', help_text='Bioavailability from DrugBank', max_length=20, verbose_name='Bioavailability (Fraction)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='drug_class',
            field=models.CharField(blank=True, default='', help_text='Drug Class from DrugBank', max_length=150, verbose_name='Drug Class'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='epa',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the EPA project', verbose_name='EPA'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchikey',
            field=models.CharField(blank=True, default='', help_text='IUPAC standard InChI key for the compound', max_length=27, verbose_name='InChI Key'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='known_drug',
            field=models.BooleanField(default=False, verbose_name='Known Drug'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='medchem_alerts',
            field=models.BooleanField(default=False, help_text='Inicates whether structural alerts are listed for this compound', verbose_name='Medchem Alerts'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_formula',
            field=models.CharField(blank=True, default='', help_text='Molecular formula of compound.', max_length=40, verbose_name='Molecular Formula'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.FloatField(blank=True, help_text='Molecular weight of the compound', null=True, verbose_name='Molecular Weight'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='mps',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the MPS project', verbose_name='MPS'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(help_text='Preferred compound name.', max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='ro3_passes',
            field=models.BooleanField(default=False, help_text='Rule of 3 passes.  It is suggested that compounds that pass all these criteria aremore likely to be hits in fragment screening.', verbose_name='Passes Rule of 3'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='ro5_violations',
            field=models.IntegerField(blank=True, help_text="Number of properties defined in Lipinski's Rule of 5 (RO5) that the compound fails.", null=True, verbose_name='Rule of 5 Violations'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='rotatable_bonds',
            field=models.IntegerField(blank=True, help_text='Number of rotatable bonds.', null=True, verbose_name='Rotatable Bonds'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, default='', help_text='Canonical smiles, generated using pipeline pilot.', max_length=1000, verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='species',
            field=models.CharField(blank=True, default='', help_text='A description of the predominant species occurring at pH 7.4 and can be acid, base, neutral or zwitterion.', max_length=10, verbose_name='Molecular Species'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='synonyms',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='synonyms'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Tags for the compound (EPA, NCATS, etc.)', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='tctc',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the TCTC project', verbose_name='TCTC'),
        ),
        migrations.AlterField(
            model_name='compoundinstance',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound', verbose_name='Compound'),
        ),
        migrations.AlterField(
            model_name='compoundinstance',
            name='lot',
            field=models.CharField(max_length=255, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='compoundinstance',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Receipt Date'),
        ),
        migrations.AlterField(
            model_name='compoundinstance',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CompoundSupplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='compoundproperty',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound', verbose_name='Compound'),
        ),
        migrations.AlterField(
            model_name='compoundproperty',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.PropertyType', verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='compoundproperty',
            name='source',
            field=models.CharField(max_length=250, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='compoundproperty',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='compoundsummary',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound', verbose_name='Compound'),
        ),
        migrations.AlterField(
            model_name='compoundsummary',
            name='source',
            field=models.CharField(max_length=250, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='compoundsummary',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='compoundsummary',
            name='summary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.SummaryType', verbose_name='Summary Type'),
        ),
        migrations.AlterField(
            model_name='compoundsupplier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='action',
            field=models.CharField(blank=True, default='', max_length=75, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound', verbose_name='Compound'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='organism',
            field=models.CharField(max_length=150, verbose_name='Organism'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='pharmacological_action',
            field=models.CharField(max_length=20, verbose_name='Pharmacological Action'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='compoundtarget',
            name='uniprot_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='UniProt ID'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='summarytype',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='summarytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
