# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 17:38


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microdevices', '0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='organmodel',
            name='alt_name',
            field=models.CharField(blank=True, default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='organmodel',
            name='base_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel'),
        ),
        migrations.AddField(
            model_name='organmodel',
            name='disease_trigger',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'Compound', b'Induced by Compound'), (b'Cells', b'Addition of Diseased Cells')], default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='organmodel',
            name='model_type',
            field=models.CharField(choices=[(b'F2', b'Fluidic-2D'), (b'F3', b'Fluidic-3D'), (b'S2', b'Static-2D'), (b'S3', b'Static-3D')], default='F3', max_length=2),
            preserve_default=False,
        ),
    ]
