# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microdevices', '0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdeferral',
            name='approval_file',
            field=models.FileField(blank=True, null=True, upload_to='deferral'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='version/ catalog#'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='column_labels',
            field=models.CharField(blank=True, default='', help_text='Space separated list of unique labels, e.g. "1 2 3 4 ...". Number of items must match number of columns.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_cross_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='assays'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_fluid_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='device fluid volume (uL)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='assays'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_length',
            field=models.FloatField(blank=True, null=True, verbose_name='length (mm)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_size_unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_type',
            field=models.CharField(choices=[('chip', 'Microchip'), ('plate', 'Plate')], max_length=8),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_width',
            field=models.FloatField(blank=True, null=True, verbose_name='width (mm)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='references',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='row_labels',
            field=models.CharField(blank=True, default='', help_text='Space separated list of unique labels, e.g. "A B C D ..." Number of items must match number of columns.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='substrate_material',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='substrate_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='substrate thickness (um)'),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='***PLEASE DO NOT INCLUDE "Admin" OR "Viewer": ONLY SELECT THE BASE GROUP (ie "Taylor_MPS" NOT "Taylor_MPS Admin")***<br>', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='pi',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='PI'),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='pi_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='PI Email'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='disease_trigger',
            field=models.CharField(blank=True, choices=[('', ''), ('Compound', 'Induced by Compound'), ('Cells', 'Addition of Diseased Cells')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='epa',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the EPA project'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='models'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='model_type',
            field=models.CharField(choices=[('F2', 'Fluidic-2D'), ('F3', 'Fluidic-3D'), ('S2', 'Static-2D'), ('S3', 'Static-3D')], max_length=2),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='mps',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the MPS project'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='references',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='tctc',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the TCTC project'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='file',
            field=models.FileField(upload_to='protocols', verbose_name='Protocol File'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='organ_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='Organ Model'),
        ),
        migrations.AlterField(
            model_name='validatedassay',
            name='assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayModel', verbose_name='Assay Model'),
        ),
        migrations.AlterField(
            model_name='validatedassay',
            name='organ_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='Organ Model'),
        ),
    ]
