# Generated by Django 2.1.9 on 2019-06-14 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0035'),
        ('microdevices', '0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrodeviceReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayReference')),
                ('reference_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.Microdevice')),
            ],
        ),
        migrations.CreateModel(
            name='OrganModelReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssayReference')),
            ],
        ),
        migrations.AlterModelOptions(
            name='organmodel',
            options={'ordering': ('name', 'organ'), 'verbose_name': 'MPS Model'},
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='organ_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='MPS Model'),
        ),
        migrations.AlterField(
            model_name='validatedassay',
            name='organ_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='MPS Model'),
        ),
        migrations.AddField(
            model_name='organmodelreference',
            name='reference_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel'),
        ),
        migrations.AlterUniqueTogether(
            name='organmodelreference',
            unique_together={('reference', 'reference_for')},
        ),
        migrations.AlterUniqueTogether(
            name='microdevicereference',
            unique_together={('reference', 'reference_for')},
        ),
    ]
