# Generated by Django 2.1.11 on 2019-09-09 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0037'),
        ('cellsamples', '0009'),
        ('diseases', '0004'),
        ('microdevices', '0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganModelCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('cell_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellType')),
                ('organ_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrganModelProtocolCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField(default=0, verbose_name='density')),
                ('passage', models.CharField(blank=True, default='', max_length=16, verbose_name='Passage#')),
                ('addition_time', models.FloatField(blank=True, null=True)),
                ('addition_location', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation')),
                ('biosensor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Biosensor')),
                ('cell_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellSample')),
                ('density_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits')),
            ],
        ),
        migrations.CreateModel(
            name='OrganModelProtocolSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('addition_time', models.FloatField(blank=True)),
                ('duration', models.FloatField(blank=True)),
                ('addition_location', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation')),
            ],
        ),
        migrations.AlterModelOptions(
            name='microdevice',
            options={'ordering': ('name', 'organ'), 'verbose_name': 'Device'},
        ),
        migrations.AlterModelOptions(
            name='organmodelprotocol',
            options={'verbose_name': 'MPS Model Version'},
        ),
        migrations.RenameField(
            model_name='organmodelprotocol',
            old_name='file',
            new_name='protocol_file',
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organmodelprotocol_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease'),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='disease_trigger',
            field=models.CharField(blank=True, choices=[('', ''), ('Compound', 'Induced by Compound'), ('Cells', 'Addition of Diseased Cells')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organmodelprotocol_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='name',
            field=models.CharField(default='TODO', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organmodelprotocol_signed_off_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organmodelprotocol',
            name='signed_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        # migrations.AlterUniqueTogether(
        #    name='organmodelprotocol',
        #    unique_together={('name', 'organ_model')},
        #),
        migrations.AddField(
            model_name='organmodelprotocolsetting',
            name='organ_model_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol'),
        ),
        migrations.AddField(
            model_name='organmodelprotocolsetting',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySetting'),
        ),
        migrations.AddField(
            model_name='organmodelprotocolsetting',
            name='unit',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits'),
        ),
        migrations.AddField(
            model_name='organmodelprotocolcell',
            name='organ_model_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol'),
        ),
    ]
