# Generated by Django 2.2.9 on 2020-02-06 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microdevices', '0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',), 'verbose_name': 'Manufacturer'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Version/Catalog#'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.MicrophysiologyCenter', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_cross_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='assays', verbose_name='Device Cross Section Image'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_fluid_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Device Fluid Volume (uL)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='assays', verbose_name='Device Image'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_size_unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Device Size Unit'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_type',
            field=models.CharField(choices=[('chip', 'Microchip'), ('plate', 'Plate')], max_length=8, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='device_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width (mm)'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='number_of_columns',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Number of Columns'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='number_of_rows',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Number of Row'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Organ', verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='substrate_material',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Substrate Material'),
        ),
        migrations.AlterField(
            model_name='microdevice',
            name='substrate_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Substrate Thickness (um)'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Alternative Name'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='base_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='Base Model'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.MicrophysiologyCenter', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.Microdevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='disease_trigger',
            field=models.CharField(blank=True, choices=[('', ''), ('Compound', 'Induced by Compound'), ('Cells', 'Addition of Diseased Cells')], default='', max_length=10, verbose_name='Disease Trigger'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='epa',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the EPA project', verbose_name='EPA'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='models', verbose_name='Model Image'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='model_type',
            field=models.CharField(choices=[('F2', 'Fluidic-2D'), ('F3', 'Fluidic-3D'), ('S2', 'Static-2D'), ('S3', 'Static-3D')], max_length=2, verbose_name='Model Type'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='mps',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the MPS project', verbose_name='MPS'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Organ', verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='organmodel',
            name='tctc',
            field=models.BooleanField(default=False, help_text='Whether this compound is part of the TCTC project', verbose_name='TCTC'),
        ),
        migrations.AlterField(
            model_name='organmodelcell',
            name='cell_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellType', verbose_name='Cell Type'),
        ),
        migrations.AlterField(
            model_name='organmodelcell',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='organmodelcell',
            name='organ_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='MPS Model'),
        ),
        migrations.AlterField(
            model_name='organmodellocation',
            name='notes',
            field=models.CharField(max_length=1024, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='organmodellocation',
            name='organ_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModel', verbose_name='MPS Model'),
        ),
        migrations.AlterField(
            model_name='organmodellocation',
            name='sample_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Sample Location'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='disease_trigger',
            field=models.CharField(blank=True, choices=[('', ''), ('Compound', 'Induced by Compound'), ('Cells', 'Addition of Diseased Cells')], default='', max_length=10, verbose_name='Disease Trigger'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocol',
            name='version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='addition_location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Addition Location'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='addition_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Addition Time'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='biosensor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Biosensor', verbose_name='Biosensor'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='cell_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellSample', verbose_name='Cell Sample'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='density',
            field=models.FloatField(default=0, verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='density_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Density Unit'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolcell',
            name='organ_model_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol', verbose_name='MPS Model Protocol'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='addition_location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySampleLocation', verbose_name='Addition Location'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='addition_time',
            field=models.FloatField(blank=True, verbose_name='Addition Time'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='duration',
            field=models.FloatField(blank=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='organ_model_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microdevices.OrganModelProtocol', verbose_name='MPS Model Protocol'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.AssaySetting', verbose_name='Setting'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='unit',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, to='assays.PhysicalUnits', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='organmodelprotocolsetting',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
    ]
