# Generated by Django 2.2.15 on 2020-11-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('microdevices', '0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='microphysiologycenter',
            name='accessible_groups',
            field=models.ManyToManyField(blank=True, help_text='***PLEASE DO NOT INCLUDE "Admin" OR "Viewer": ONLY SELECT THE BASE GROUP (ie "Taylor_MPS" NOT "Taylor_MPS Admin")***<br>', related_name='center_accessible_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='microphysiologycenter',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='***PLEASE DO NOT INCLUDE "Admin" OR "Viewer": ONLY SELECT THE BASE GROUP (ie "Taylor_MPS" NOT "Taylor_MPS Admin")***<br>', related_name='center_groups', to='auth.Group'),
        ),
    ]
