# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 18:13


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default=b'')),
                ('overview_state_blurb', models.TextField(blank=True, default=b'', help_text=b'NOTE: Use HTML tags to create lists.')),
                ('overview_state_image', models.ImageField(blank=True, null=True, upload_to=b'disease_images')),
                ('biology_blurb', models.TextField(blank=True, default=b'', help_text=b'NOTE: Use HTML tags to create lists.')),
                ('biology_image', models.ImageField(blank=True, null=True, upload_to=b'disease_images')),
                ('biology_kegg_pathway_map', models.ImageField(blank=True, help_text=b'NOTE: Save and upload the KEGG Pathway Map.', null=True, upload_to=b'disease_images')),
                ('biology_kegg_pathway_url', models.CharField(default=b'https://www.genome.jp/kegg/', help_text=b'Example: http://www.genome.jp/kegg-bin/show_pathway?hsa04932 (Direct link to KEGG Pathway Map)', max_length=400)),
                ('biology_kegg_url', models.CharField(default=b'https://www.genome.jp/kegg/', help_text=b'Example: https://www.genome.jp/dbget-bin/www_bget?ds:H01333 (Link to KEGG Disease Entry)', max_length=400)),
                ('biology_genomic_geo_url', models.CharField(blank=True, max_length=200, null=True)),
                ('biology_genomic_omim_url', models.CharField(blank=True, help_text=b"NOTE: On the OMIM result page for this disease, click the blue 'Gene Map Table' button before copying the URL.", max_length=200, null=True)),
                ('biology_genomic_exsnp_url', models.CharField(blank=True, max_length=200, null=True)),
                ('biology_genomic_diseasesorg_url', models.CharField(blank=True, max_length=200, null=True)),
                ('clinicaldata_blurb', models.TextField(blank=True, default=b'', help_text=b'NOTE: Use HTML tags to create lists.')),
                ('clinicaldata_image', models.ImageField(blank=True, null=True, upload_to=b'disease_images')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_modified_by', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_signed_off_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
