# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_clinical_data_table_name', models.CharField(blank=True, default=b'', max_length=200)),
                ('overview_clinical_data_table_description', models.TextField(blank=True, default=b'')),
                ('overview_clinical_data_table_num_results', models.IntegerField(default=0)),
                ('overview_clinical_data_table_num_phaseI', models.IntegerField(default=0)),
                ('overview_clinical_data_table_num_phaseII', models.IntegerField(default=0)),
                ('overview_clinical_data_table_num_phaseIII', models.IntegerField(default=0)),
                ('overview_clinical_data_table_num_phaseIV', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseBiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseClinicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseDataAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseDiseaseModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='disease_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='disease_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_biology_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_biology_image_path',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_image_path',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_data_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_data_image_path',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_models_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_models_image_path',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_models_list',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_state_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_state_image_path',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='diseasediseasemodels',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease'),
        ),
        migrations.AddField(
            model_name='diseasedataanalysis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease'),
        ),
        migrations.AddField(
            model_name='diseaseclinicaldata',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease'),
        ),
        migrations.AddField(
            model_name='diseasebiology',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease'),
        ),
    ]
