# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='biology_blurb',
            field=models.TextField(blank=True, default='', help_text='NOTE: Use HTML tags to create lists.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='biology_genomic_omim_url',
            field=models.CharField(blank=True, help_text="NOTE: On the OMIM result page for this disease, click the blue 'Gene Map Table' button before copying the URL.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='biology_image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='biology_kegg_pathway_map',
            field=models.ImageField(blank=True, help_text='NOTE: Save and upload the KEGG Pathway Map.', null=True, upload_to='disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='biology_kegg_pathway_url',
            field=models.CharField(default='https://www.genome.jp/kegg/', help_text='Example: http://www.genome.jp/kegg-bin/show_pathway?hsa04932 (Direct link to KEGG Pathway Map)', max_length=400),
        ),
        migrations.AlterField(
            model_name='disease',
            name='biology_kegg_url',
            field=models.CharField(default='https://www.genome.jp/kegg/', help_text='Example: https://www.genome.jp/dbget-bin/www_bget?ds:H01333 (Link to KEGG Disease Entry)', max_length=400),
        ),
        migrations.AlterField(
            model_name='disease',
            name='clinicaldata_blurb',
            field=models.TextField(blank=True, default='', help_text='NOTE: Use HTML tags to create lists.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='clinicaldata_image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='disease',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_state_blurb',
            field=models.TextField(blank=True, default='', help_text='NOTE: Use HTML tags to create lists.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_state_image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images'),
        ),
    ]
