# Generated by Django 2.1.8 on 2019-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='biology_drugbank_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='biology_metabolomicsworkbench_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='biology_pharmagkb_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
