# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_auto_20180504_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='overview_biology_image_path',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='overview_clinicaldata_image_path',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='overview_data_image_path',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='overview_models_image_path',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='overview_models_list',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='overview_state_image_path',
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_biology_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'studies'),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'studies'),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_data_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'studies'),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_models_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'studies'),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_state_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'studies'),
        ),
    ]
