# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_auto_20180507_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasebiology',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='diseaseclinicaldata',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='diseasedataanalysis',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='diseasediseasemodels',
            name='disease',
        ),
        migrations.DeleteModel(
            name='DiseaseBiology',
        ),
        migrations.DeleteModel(
            name='DiseaseClinicalData',
        ),
        migrations.DeleteModel(
            name='DiseaseDataAnalysis',
        ),
        migrations.DeleteModel(
            name='DiseaseDiseaseModels',
        ),
    ]
