# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_auto_20180508_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicalTrial',
        ),
        migrations.AddField(
            model_name='disease',
            name='biology_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='biology_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
        migrations.AddField(
            model_name='disease',
            name='kegg_pathway_map',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_biology_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_clinicaldata_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_data_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_models_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='overview_state_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
    ]
