# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_auto_20180509_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='clinicaldata_blurb',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='disease',
            name='clinicaldata_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'disease_images'),
        ),
    ]
