# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_auto_20180509_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_num_phaseI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_num_phaseII',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_num_phaseIII',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_num_phaseIV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='overview_clinicaldata_num_results',
            field=models.IntegerField(default=0),
        ),
    ]
