# -*- coding: utf-8 -*-


from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(null=True, blank=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('chemblid', models.TextField(help_text=b'Enter a ChEMBL id, e.g. CHEMBL1217643, and click Retrieve to get target information automatically.', unique=True, null=True, verbose_name=b'ChEMBL ID', blank=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('organism', models.TextField(null=True, blank=True)),
                ('assay_type', models.CharField(max_length=1, choices=[(b'B', b'Binding'), (b'F', b'Functional'), (b'A', b'ADMET')])),
                ('journal', models.TextField(null=True, blank=True)),
                ('strain', models.TextField(null=True, blank=True)),
                ('last_update', models.DateField(help_text=b'Last time when activities associated with the assay were updated.', null=True, blank=True)),
                ('created_by', models.ForeignKey(related_name='assay_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(related_name='assay_modified_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('signed_off_by', models.ForeignKey(related_name='assay_signed_off_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
            ],
            options={
                'ordering': ('chemblid',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Bioactivity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(null=True, blank=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('target_confidence', models.IntegerField(null=True, blank=True)),
                ('bioactivity_type', models.TextField(null=True, verbose_name=b'name', blank=True)),
                ('standard_name', models.TextField(null=True, blank=True)),
                ('operator', models.TextField(null=True, blank=True)),
                ('units', models.TextField(null=True, blank=True)),
                ('value', models.FloatField(null=True, blank=True)),
                ('standardized_units', models.TextField(null=True, verbose_name=b'std units', blank=True)),
                ('standardized_value', models.FloatField(null=True, verbose_name=b'std vals', blank=True)),
                ('activity_comment', models.TextField(null=True, blank=True)),
                ('reference', models.TextField(null=True, blank=True)),
                ('name_in_reference', models.TextField(null=True, blank=True)),
                ('chembl_assay_type', models.TextField(default=b'', null=True, blank=True)),
                ('assay', models.ForeignKey(to='bioactivities.Assay', on_delete=models.CASCADE)),
                ('compound', models.ForeignKey(related_name='bioactivity_compound', to='compounds.Compound', on_delete=models.CASCADE)),
                ('created_by', models.ForeignKey(related_name='bioactivity_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(related_name='bioactivity_modified_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('parent_compound', models.ForeignKey(related_name='bioactivity_parent', to='compounds.Compound', on_delete=models.CASCADE)),
                ('signed_off_by', models.ForeignKey(related_name='bioactivity_signed_off_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
            ],
            options={
                'ordering': ('compound', 'bioactivity_type'),
                'verbose_name_plural': 'bioactivities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BioactivityType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(null=True, blank=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('chembl_bioactivity', models.TextField(default=b'')),
                ('chembl_unit', models.TextField(default=b'')),
                ('scale_factor', models.FloatField(default=1, null=True, blank=True)),
                ('mass_flag', models.CharField(default=b'N', max_length=8, choices=[(b'Y', b'Yes'), (b'N', b'No')])),
                ('standard_name', models.TextField(default=b'')),
                ('description', models.TextField(default=b'')),
                ('standard_unit', models.TextField(default=b'')),
                ('created_by', models.ForeignKey(related_name='bioactivitytype_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(related_name='bioactivitytype_modified_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('signed_off_by', models.ForeignKey(related_name='bioactivitytype_signed_off_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
            ],
            options={
                'ordering': ('chembl_bioactivity', 'chembl_unit'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PubChemBioactivity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(null=True, blank=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('assay_id', models.TextField(verbose_name=b'Assay ID')),
                ('value', models.FloatField(verbose_name=b'Value (uM)')),
                ('source', models.TextField(default=b'', null=True, blank=True)),
                ('activity_name', models.TextField(default=b'', verbose_name=b'Activity Name')),
                ('assay_name', models.TextField(default=b'', null=True, verbose_name=b'Assay Name', blank=True)),
                ('compound', models.ForeignKey(to='compounds.Compound', on_delete=models.CASCADE)),
                ('created_by', models.ForeignKey(related_name='pubchembioactivity_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(related_name='pubchembioactivity_modified_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('signed_off_by', models.ForeignKey(related_name='pubchembioactivity_signed_off_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PubChemTarget',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(null=True, blank=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('name', models.TextField(default=b'', help_text=b'Preferred target name.')),
                ('organism', models.TextField(default=b'')),
                ('GI', models.TextField(verbose_name=b'NCBI GI')),
                ('created_by', models.ForeignKey(related_name='pubchemtarget_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(related_name='pubchemtarget_modified_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('signed_off_by', models.ForeignKey(related_name='pubchemtarget_signed_off_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('signed_off_date', models.DateTimeField(null=True, blank=True)),
                ('locked', models.BooleanField(default=False, help_text=b'Check the box and save to lock the entry. Uncheck and save to enable editing.')),
                ('name', models.TextField(help_text=b'Preferred target name.')),
                ('synonyms', models.TextField(null=True, blank=True)),
                ('chemblid', models.TextField(help_text=b'Enter a ChEMBL id, e.g. CHEMBL260, and click Retrieve to get target information automatically.', unique=True, null=True, verbose_name=b'ChEMBL ID', blank=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('gene_names', models.TextField(null=True, blank=True)),
                ('organism', models.TextField(null=True, blank=True)),
                ('uniprot_accession', models.TextField(null=True, blank=True)),
                ('target_type', models.TextField(null=True, blank=True)),
                ('last_update', models.DateField(help_text=b'Last time when activities associated with the target were updated.', null=True, blank=True)),
                ('created_by', models.ForeignKey(related_name='target_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(related_name='target_modified_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('signed_off_by', models.ForeignKey(related_name='target_signed_off_by', blank=True, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='pubchembioactivity',
            name='target',
            field=models.ForeignKey(default=None, blank=True, to='bioactivities.PubChemTarget', null=True, verbose_name=b'Target', on_delete=models.CASCADE),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bioactivity',
            name='target',
            field=models.ForeignKey(to='bioactivities.Target', on_delete=models.CASCADE),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='bioactivity',
            unique_together=set([('assay', 'target', 'compound')]),
        ),
    ]
