# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioactivities', '0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='assay_type',
            field=models.CharField(choices=[('B', 'Binding'), ('F', 'Functional'), ('A', 'ADMET'), ('P', 'Physicochemical'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='assay',
            name='chemblid',
            field=models.TextField(blank=True, default='', help_text='Enter a ChEMBL id, e.g. CHEMBL1217643, and click Retrieve to get target information automatically.', verbose_name='ChEMBL ID'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assay',
            name='journal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assay',
            name='last_update',
            field=models.DateField(blank=True, help_text='Last time when activities associated with the assay were updated.', null=True),
        ),
        migrations.AlterField(
            model_name='assay',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Assay Name'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='organism',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assay',
            name='pubchem_id',
            field=models.TextField(blank=True, default='', verbose_name='PubChem ID'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assay',
            name='source_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assay',
            name='strain',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assay',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioactivities.Target', verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='activity_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='bioactivity_type',
            field=models.TextField(blank=True, default='', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='data_validity',
            field=models.CharField(blank=True, choices=[('R', 'Outside typical range'), ('T', 'Potential transcription error'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='name_in_reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='normalized_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Normalized Value'),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='operator',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='standard_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='standardized_units',
            field=models.TextField(blank=True, default='', verbose_name='std units'),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='standardized_value',
            field=models.FloatField(blank=True, null=True, verbose_name='std vals'),
        ),
        migrations.AlterField(
            model_name='bioactivity',
            name='units',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='chembl_bioactivity',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='chembl_unit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='mass_flag',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=8),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='standard_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bioactivitytype',
            name='standard_unit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubchemassay',
            name='aid',
            field=models.TextField(verbose_name='Assay ID'),
        ),
        migrations.AlterField(
            model_name='pubchemassay',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubchemassay',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='pubchemassay',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Assay Name'),
        ),
        migrations.AlterField(
            model_name='pubchemassay',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubchemassay',
            name='source_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='activity_name',
            field=models.TextField(blank=True, default='', verbose_name='Activity Name'),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='data_validity',
            field=models.CharField(blank=True, choices=[('R', 'Outside typical range'), ('T', 'Potential transcription error'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='normalized_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Normalized Value'),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='outcome',
            field=models.TextField(blank=True, default='', verbose_name='Bioactivity Outcome'),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioactivities.Target', verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='pubchembioactivity',
            name='value',
            field=models.FloatField(verbose_name='Value (uM)'),
        ),
        migrations.AlterField(
            model_name='pubchemtarget',
            name='GI',
            field=models.TextField(blank=True, default='', verbose_name='NCBI GI'),
        ),
        migrations.AlterField(
            model_name='pubchemtarget',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='pubchemtarget',
            name='name',
            field=models.TextField(blank=True, default='', help_text='Preferred target name.'),
        ),
        migrations.AlterField(
            model_name='pubchemtarget',
            name='organism',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubchemtarget',
            name='target_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='GI',
            field=models.TextField(blank=True, default='', verbose_name='NCBI GI'),
        ),
        migrations.AlterField(
            model_name='target',
            name='chemblid',
            field=models.TextField(blank=True, default='', help_text='Enter a ChEMBL id, e.g. CHEMBL260, and click Retrieve to get target information automatically.', verbose_name='ChEMBL ID'),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='gene_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_update',
            field=models.DateField(blank=True, help_text='Last time when activities associated with the target were updated.', null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.TextField(help_text='Preferred target name.'),
        ),
        migrations.AlterField(
            model_name='target',
            name='organism',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='synonyms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='uniprot_accession',
            field=models.TextField(blank=True, default=''),
        ),
    ]
