# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellsamples', '0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosensor',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='biosensor',
            name='lot_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lot#'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Barcode/Lot#'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='cell_image',
            field=models.ImageField(blank=True, null=True, upload_to='cellsamples'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Check box to flag for review'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='group',
            field=models.ForeignKey(help_text='Bind to a group', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='isolation_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='Isolation'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='isolation_method',
            field=models.CharField(blank=True, max_length=255, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='isolation_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('N', 'Not-specified'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='reason_for_flag',
            field=models.CharField(blank=True, default='', help_text='Reason for why this entry was flagged', max_length=300),
        ),
        migrations.AlterField(
            model_name='cellsubtype',
            name='cell_subtype',
            field=models.CharField(help_text='Example: motor (type of neuron), skeletal (type of muscle), etc.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cellsubtype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='cell_type',
            field=models.CharField(help_text='Example: hepatocyte, muscle, kidney, etc', max_length=255),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='species',
            field=models.CharField(blank=True, choices=[('Human', 'Human'), ('Rat', 'Rat'), ('Mouse', 'Mouse')], default='Human', max_length=10),
        ),
        migrations.AlterField(
            model_name='organ',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
    ]
