# Generated by Django 2.2.9 on 2020-02-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellsamples', '0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biosensor',
            options={'ordering': ('name',), 'verbose_name': 'Cell Biosensor'},
        ),
        migrations.AlterModelOptions(
            name='cellsubtype',
            options={'ordering': ('cell_subtype',), 'verbose_name': 'Cell Subtype'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Cell Supplier'},
        ),
        migrations.AlterField(
            model_name='biosensor',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='biosensor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='biosensor',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='biosensor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='cell_image',
            field=models.ImageField(blank=True, null=True, upload_to='cellsamples', verbose_name='Cell Image'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='cell_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellSubtype', verbose_name='Cell Subtype'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='cell_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellType', verbose_name='Cell Type'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='isolation_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='Isolation Date'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='isolation_method',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Isolation Method'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='isolation_notes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Isolation Notes'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patient Age'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='patient_condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Patient Condition'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('N', 'Not-specified'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=1, verbose_name='Patient Sex'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='percent_viability',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Viability'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Receipt Date'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='viable_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Viable Count'),
        ),
        migrations.AlterField(
            model_name='cellsubtype',
            name='cell_subtype',
            field=models.CharField(help_text='Example: motor (type of neuron), skeletal (type of muscle), etc.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cellsubtype',
            name='cell_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellType', verbose_name='Cell Type'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='cell_type',
            field=models.CharField(help_text='Example: hepatocyte, muscle, kidney, etc', max_length=255, verbose_name='Cell Type'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.Organ', verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
    ]
