# Generated by Django 2.2.15 on 2020-11-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellsamples', '0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellsample',
            name='cell_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellsamples.CellSubtype', verbose_name='Cell Origin'),
        ),
    ]
