# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangovoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False, help_text='Do not show who sent this', verbose_name='Anonymous'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='private',
            field=models.BooleanField(blank=True, default=False, help_text='Hide from public pages. Only site administrators will be able to view and respond to this', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='status',
            name='default',
            field=models.BooleanField(blank=True, default=False, help_text='New feedback will have this status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
