# Generated by Django 2.2.9 on 2020-02-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangovoice', '0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='private',
            field=models.BooleanField(blank=True, default=True, help_text='Hide from public pages. Only site administrators will be able to view and respond to this', verbose_name='Private'),
        ),
    ]
