# Generated by Django 2.1.8 on 2019-04-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='definition',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='reference',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='resource',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcesubtype',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='resourcesubtype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='resourcesubtype',
            name='name',
            field=models.TextField(max_length=40, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to lock the entry. Uncheck and save to enable editing.'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='resource_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceSubtype', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='resource_type_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Type'),
        ),
    ]
