# Generated by Django 2.1.11 on 2019-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
        migrations.AlterField(
            model_name='resourcesubtype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='locked',
            field=models.BooleanField(default=False, help_text='Check the box and save to block automatic migration to *Public Access*, 1-year after sign off. Uncheck and save to enable automatic migration to *Public Access*, 1-year after sign off. While this is checked, automatic approvals for Stakeholders are also prevented.', verbose_name='Keep Private Indefinitely (Locked)'),
        ),
    ]
