# Generated by Django 2.2.15 on 2020-09-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'verbose_name': 'Help - Glossary', 'verbose_name_plural': 'Help - Glossary'},
        ),
        migrations.AddField(
            model_name='definition',
            name='data_sources',
            field=models.ManyToManyField(blank=True, limit_choices_to={'help_category': 'source'}, related_name='_definition_data_sources_+', to='resources.Definition'),
        ),
        migrations.AddField(
            model_name='definition',
            name='glossary_display',
            field=models.BooleanField(default=True, help_text='Check to display in the glossary.'),
        ),
        migrations.AddField(
            model_name='definition',
            name='help_category',
            field=models.CharField(blank=True, choices=[('feature', 'feature'), ('source', 'source'), ('component-cell', 'component-cell'), ('component-assay', 'component-assay'), ('component-compound', 'component-compound'), ('component-model', 'component-model')], default='', help_text='Used in generating help tables.', max_length=30),
        ),
        migrations.AddField(
            model_name='definition',
            name='help_display',
            field=models.BooleanField(default=True, help_text='Check to display in tables and other locations in the help page (does not apply to the glossary).'),
        ),
        migrations.AddField(
            model_name='definition',
            name='help_order',
            field=models.IntegerField(blank=True, default=0, help_text='Used in generating help tables. Order is way they will be listed in their respective tables. Make sure they are unique within a help_category.'),
        ),
        migrations.AddField(
            model_name='definition',
            name='help_reference',
            field=models.URLField(blank=True, default=''),
        ),
    ]
