# Generated by Django 2.2.15 on 2020-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='help_category',
            field=models.CharField(blank=True, choices=[('feature', 'Database Feature'), ('source', 'Reference Data Source'), ('component-cell', 'Cell Component'), ('component-assay', 'Assay Component'), ('component-compound', 'Compound Component'), ('component-model', 'Model Component'), ('component-compound', 'Compound Component'), ('permission', 'Permission Structure'), ('organization-study', 'Study Organization')], default='', help_text='Used in generating help tables.', max_length=30),
        ),
    ]
